version: "3.9"

services:
  api:
    image: golang:1.19-alpine
    depends_on:
      - db_mysql
    env_file: .env
    command: sh -c "sleep 4 && go run cmd/api/main.go"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:80"
  migrations:
    image: golang:1.19-alpine
    depends_on:
      - db_mysql
    env_file: .env
    command: sh -c "sleep 4 && go run cmd/migration/main.go"
    volumes:
      - .:/app
    working_dir: /app
  db_mysql:
    env_file: .env
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3310:3306"

volumes:
  mysql-db: