// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	DeleteSpaceshipById(ctx context.Context, id int32) error
	GetSpaceShipById(ctx context.Context, id int32) (Spaceship, error)
	GetSpaceShips(ctx context.Context) ([]Spaceship, error)
	InsertSpaceship(ctx context.Context, arg InsertSpaceshipParams) error
	UpdateSpaceship(ctx context.Context, arg UpdateSpaceshipParams) error
}

var _ Querier = (*Queries)(nil)
